baseURL = 'https://sujtfri.github.io/matjaz.kukar/' # change member_repository to your repository name
theme = ["hugo-cloak-email","sujt_theme"]

[params]
rootURL = "https://sujtfri.github.io/"

[languages]
  [languages.en]
    title = 'SUJT'
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
    [languages.en.params]
      flag = "flag-icon-us"
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "About"
        url = "/" 
        weight = 100
      [[languages.en.menus.main]]
        name = "Teaching"
        url = "/teaching/" 
        weight = 200
      [[languages.en.menus.main]]
        name = "Bibliography"
        url = "/bibliography/" 
        weight = 250
      [[languages.en.menus.main]]
        name = "Projects"
        url = "/projects/" 
        weight = 300
      [[languages.en.menus.main]]
        name = "Blog"
        url = "/blog/" 
        weight = 400

  [languages.si]
    title = 'SUJT'
    contentDir = 'content/slovene'
    languageName = 'Slovenščina'
    weight = 10
    [languages.si.params]
      flag = "flag-icon-si"
    [languages.si.menus]
      [[languages.si.menus.main]]
        name = "O meni"
        url = "/si/" 
        weight = 100
      [[languages.si.menus.main]]
        name = "Poučevanje"
        url = "/si/teaching/" 
        weight = 200
      [[languages.si.menus.main]]
        name = "Bibliografija"
        url = "/si/bibliography/" 
        weight = 250
      [[languages.si.menus.main]]
        name = "Projekti"
        url = "/si/projects/" 
        weight = 300
      [[languages.si.menus.main]]
        name = "Blog"
        url = "/si/blog/" 
        weight = 400

[markup.goldmark.renderer] 
  unsafe= true

